In [ ]:
import pandas as pd

In [38]:
miami_heat = pd.DataFrame(
    {
        'Age': [27, 29, 23, 31, 30],
        'Position': ['PG', 'SG', 'SF', 'PF', 'C'],
        'Salary': [10_000_000, 30_000_000, 45_000_000, 7_000_000, 20_000_000],
        'Starting?': [True, True, True, True, True],
    },
    index=['Mario Chalmers', 'Dwayne Wade', 'LeBron James', 'Shane Battier', 'Chris Bosh']
)

In [39]:
miami_heat

                Age Position    Salary  Starting?
Mario Chalmers   27       PG  10000000       True
Dwayne Wade      29       SG  30000000       True
LeBron James     23       SF  45000000       True
Shane Battier    31       PF   7000000       True
Chris Bosh       30        C  20000000       True

In [40]:
miami_heat.head(4)

                Age Position    Salary  Starting?
Mario Chalmers   27       PG  10000000       True
Dwayne Wade      29       SG  30000000       True
LeBron James     23       SF  45000000       True
Shane Battier    31       PF   7000000       True

In [41]:
miami_heat.tail(2)

               Age Position    Salary  Starting?
Shane Battier   31       PF   7000000       True
Chris Bosh      30        C  20000000       True

In [42]:
miami_heat['Age']

Mario Chalmers    27
Dwayne Wade       29
LeBron James      23
Shane Battier     31
Chris Bosh        30
Name: Age, dtype: int64

In [43]:
miami_heat.loc['LeBron James': 'Chris Bosh'][(miami_heat['Age'] <= 30)]

C:\Users\JJack\AppData\Local\Temp\ipykernel_32396\1178356240.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  miami_heat.loc['LeBron James': 'Chris Bosh'][(miami_heat['Age'] <= 30)]

              Age Position    Salary  Starting?
LeBron James   23       SF  45000000       True
Chris Bosh     30        C  20000000       True

In [44]:
miami_heat.iloc[2, 0]

np.int64(23)

In [45]:
miami_heat.iat[1, 2]

np.int64(30000000)

In [46]:
miami_heat.at['LeBron James', 'Position']

'SF'

In [47]:
miami_heat.info() # Provdies overview of DataFrame

<class 'pandas.DataFrame'>
Index: 5 entries, Mario Chalmers to Chris Bosh
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        5 non-null      int64
 1   Position   5 non-null      str
 2   Salary     5 non-null      int64
 3   Starting?  5 non-null      bool
dtypes: bool(1), int64(2), str(1)
memory usage: 337.0+ bytes

In [48]:
miami_heat.size # returns number of data places in DataFrame

20

In [49]:
f'${miami_heat['Salary'].mean():,.2f}'

'$22,400,000.00'

In [50]:
miami_heat.drop('Chris Bosh') # Only displays DatFrame without Chris Bosh index row

                Age Position    Salary  Starting?
Mario Chalmers   27       PG  10000000       True
Dwayne Wade      29       SG  30000000       True
LeBron James     23       SF  45000000       True
Shane Battier    31       PF   7000000       True

In [51]:
miami_heat.loc['Chris Bosh']

Age                30
Position            C
Salary       20000000
Starting?        True
Name: Chris Bosh, dtype: object

In [52]:
miami_heat.drop('Chris Bosh', inplace=True) # Permanently removes Chris Bosh from DataFrame due to inplace param being set to True

In [53]:
miami_heat.loc['Chris Bosh'] # No longer in DataFrame

KeyError: 'Chris Bosh'

In [54]:
miami_heat.sample()

               Age Position   Salary  Starting?
Shane Battier   31       PF  7000000       True

In [55]:
miami_heat.describe()

            Age        Salary
count   4.00000  4.000000e+00
mean   27.50000  2.300000e+07
std     3.41565  1.786990e+07
min    23.00000  7.000000e+06
25%    26.00000  9.250000e+06
50%    28.00000  2.000000e+07
75%    29.50000  3.375000e+07
max    31.00000  4.500000e+07

In [56]:
miami_heat.columns

Index(['Age', 'Position', 'Salary', 'Starting?'], dtype='str')

In [57]:
miami_heat.index

Index(['Mario Chalmers', 'Dwayne Wade', 'LeBron James', 'Shane Battier'], dtype='str')

In [58]:
miami_heat

                Age Position    Salary  Starting?
Mario Chalmers   27       PG  10000000       True
Dwayne Wade      29       SG  30000000       True
LeBron James     23       SF  45000000       True
Shane Battier    31       PF   7000000       True

In [59]:
miami_heat.describe()

            Age        Salary
count   4.00000  4.000000e+00
mean   27.50000  2.300000e+07
std     3.41565  1.786990e+07
min    23.00000  7.000000e+06
25%    26.00000  9.250000e+06
50%    28.00000  2.000000e+07
75%    29.50000  3.375000e+07
max    31.00000  4.500000e+07

In [60]:
miami_heat.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Mario Chalmers to Shane Battier
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        4 non-null      int64
 1   Position   4 non-null      str
 2   Salary     4 non-null      int64
 3   Starting?  4 non-null      bool
dtypes: bool(1), int64(2), str(1)
memory usage: 304.0+ bytes

In [63]:
miami_heat

                Age Position    Salary  Starting?
Mario Chalmers   27       PG  10000000      False
Dwayne Wade      29       SG  30000000      False
LeBron James     23       SF  45000000      False
Shane Battier    31       PF   7000000      False